### ISSUE TITLE
F&O provision is missing

### ISSUE THREAD

**Issue by QAJaneHowell** [MicrosoftLearning/MB-901T00-Microsoft-Dynamics-365-Fundamentals#4]
Unable to complete F&O labs due to there being no provision of F&O. 
<img width="957" alt="F O" src="https://user-images.githubusercontent.com/59439005/86154572-2b0c3780-bafb-11ea-9d00-6df9508cf3b4.png">

**Comment by CeleneA** [comment]
This has been addressed
